# Generated by Django 5.0.6 on 2024-07-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Writer', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
