# Generated by Django 5.0.6 on 2024-07-03 19:08

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_darkmode', models.BooleanField(default=False, verbose_name='Dark Mode')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Login.article', verbose_name='Makale')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Login.reader', verbose_name='Okuyucu')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=1024, verbose_name='İşlem')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_darkmode', models.BooleanField(default=False, verbose_name='Dark Mode')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Silindi')),
                ('delete_date', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Tarihi')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Url')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.writer', verbose_name='Yazar'),
        ),
    ]
