# Generated by Django 5.0.6 on 2024-07-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_writer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biyografi'),
        ),
    ]
