# Generated by Django 5.0.6 on 2024-07-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
