# Generated by Django 5.0.6 on 2024-07-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
